/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author monic
 */
public class Registrar extends javax.swing.JFrame {

    private boolean esEdicion = false;
    private String codigoOriginal = null;

    private static final java.time.format.DateTimeFormatter FMT
            = java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");

    // FORMATO DE REGISTRO. 
    private String genIdIntangible() {
        return "LIC" + String.format("%06d", (int) (System.currentTimeMillis() % 1_000_000));
    }

    private String genCodigo() {
        return "COD-" + System.currentTimeMillis();
    }

    private LocalDate parseFecha(String s) {
        if (s == null) {
            return null;
        }
        s = s.trim();
        if (s.isEmpty()) {
            return null;
        }

        String[] patrones = {"d/M/yyyy", "dd/MM/yyyy", "yyyy-MM-dd"};
        for (String p : patrones) {
            try {
                return LocalDate.parse(s, java.time.format.DateTimeFormatter.ofPattern(p));
            } catch (Exception ignore) {
            }
        }
        return null;
    }

    private String aVidaTexto(String nStr) {
        if (nStr == null || nStr.trim().isEmpty()) {
            return "12 meses";
        }
        String d = nStr.replaceAll("\\D+", "");
        if (d.isEmpty()) {
            return "12 meses";
        }
        int n = Integer.parseInt(d);
        return (n == 1) ? "1 mes" : (n + " meses");
    }

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        esEdicion = false;
        btnGuardar.setText("Guardar");

        //***************** BARRA DE NAVEGACION***************************
        // GESTION INTANGIBLE
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                new BUSQUEDA().setVisible(true);
                dispose();
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });
        // REPORTE
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent e) {
                new Reporte().setVisible(true);
                dispose();
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });
        // HISTORIAL 
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                new Historial().setVisible(true);
                dispose();
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });
        // MENU
        javax.swing.JMenuItem miSalir = new javax.swing.JMenuItem("Salir");
        miSalir.addActionListener(e -> System.exit(0));
        jMenu1.removeAll();

        //***************** BARRA DE NAVEGACION***************************
    }

// ====================CONSTRUCTORES REGISTRO /ACTUALIZAR =====================
    public Registrar(String codigo, String nombre, String tipo,
            String fechaAdqYYYYMMDD, String costo, String vidaUtil) {
        initComponents();
        esEdicion = true;
        codigoOriginal = codigo;
        btnGuardar.setText("Actualizar");

        //AJUSTE 
        txtNombre1.setText(nombre);
        cmbTipo.setSelectedItem(tipo);
        txtFechaAdq.setText(fechaAdqYYYYMMDD);
        txtCosto.setText(costo);
        txtVidaUtil.setText(vidaUtil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtVersion = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        txtFechaAdq = new javax.swing.JFormattedTextField();
        txtFechaVenc = new javax.swing.JFormattedTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        txtVidaUtil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtIDProveedor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro/Actualizacion de Licencia ");

        jLabel2.setText("Nombre");

        jLabel3.setText("Tipo de Licencia");

        jLabel4.setText("Fecha Vencimiento ");

        jLabel5.setText("Fecha Adquisicion");
        jLabel5.setToolTipText("");

        jLabel6.setText("Vida Util");

        jLabel7.setText("Costo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVersionActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Perpetua" }));

        txtFechaAdq.setText("../../....");

        txtFechaVenc.setText("../../....");

        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre del Proveedor ");

        jLabel9.setText("ID Proveedor ");

        jLabel10.setText("Version");

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtIDProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVidaUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 284, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVidaUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jMenu1.setText("Menú");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestion de Intangible ");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes ");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Historial ");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombreIntangible = txtNombre1.getText().trim();
        String version = txtVersion.getText().trim();
        String nombreProv = txtNombreProveedor.getText().trim();
        String tipoLic = cmbTipo.getSelectedItem().toString();
        String vidaTxt = aVidaTexto(txtVidaUtil.getText());
        LocalDate fAdq = parseFecha(txtFechaAdq.getText());
        LocalDate fVenc = parseFecha(txtFechaVenc.getText());

        if (nombreIntangible.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Nombre es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombre1.requestFocus();
            return;
        }
        if (version.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La Versión es obligatoria.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtVersion.requestFocus();
            return;
        }
        if (nombreProv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Nombre del Proveedor es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombreProveedor.requestFocus();
            return;
        }

        java.math.BigDecimal costo;
        try {
            costo = new java.math.BigDecimal(txtCosto.getText().trim());
            if (costo.compareTo(java.math.BigDecimal.ZERO) < 0) {
                throw new NumberFormatException();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Costo inválido. Usa números (ej: 200 o 200.00).", "Validación", JOptionPane.WARNING_MESSAGE);
            txtCosto.requestFocus();
            return;
        }

        if (fAdq == null) {
            fAdq = LocalDate.now();
        }
        if (fVenc == null) {
            String d = vidaTxt.replaceAll("\\D+", "");
            if (!d.isEmpty()) {
                fVenc = fAdq.plusMonths(Integer.parseInt(d));
            }
        }

        // ======= ACTUALIZAR =======
        if (esEdicion) {
            String sql = "UPDATE intangible "
                    + "SET nombre_intangible=?, version=?, nombre_proveedor=?, "
                    + "    tipo_licencia_=?, fecha_adquisicion=?, fecha_vencimiento=?, "
                    + "    costo=?, vida_util=? "
                    + "WHERE codigo_=?";

            try (java.sql.Connection cn = Conexion.getConnection(); java.sql.PreparedStatement ps = cn.prepareStatement(sql)) {

                ps.setString(1, nombreIntangible);
                ps.setString(2, version);
                ps.setString(3, nombreProv);
                ps.setString(4, tipoLic);
                ps.setDate(5, java.sql.Date.valueOf(fAdq));
                if (fVenc != null) {
                    ps.setDate(6, java.sql.Date.valueOf(fVenc));
                } else {
                    ps.setNull(6, java.sql.Types.DATE);
                }
                ps.setBigDecimal(7, costo);
                ps.setString(8, vidaTxt);
                ps.setString(9, codigoOriginal);

                int n = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, (n > 0 ? "Actualizado " : "Sin cambios."));
                dispose();
                return;

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "BD",
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                return;
            }
        }

        // ======= INSERT =======  
        String idIntangible = genIdIntangible();
        String codigo = genCodigo();
        String estado = "ACTIVO";

        String sql = "INSERT INTO intangible "
                + "(idintangible, version, nombre_proveedor, tipo_licencia_, codigo_, costo, vida_util, estado_, nombre_intangible, fecha_adquisicion, fecha_vencimiento) "
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?)";

        try (java.sql.Connection cn = Conexion.getConnection(); java.sql.PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setString(1, idIntangible);
            ps.setString(2, version);
            ps.setString(3, nombreProv);
            ps.setString(4, tipoLic);
            ps.setString(5, codigo);
            ps.setBigDecimal(6, costo);
            ps.setString(7, vidaTxt);
            ps.setString(8, estado);
            ps.setString(9, nombreIntangible);
            ps.setDate(10, java.sql.Date.valueOf(fAdq));
            if (fVenc != null) {
                ps.setDate(11, java.sql.Date.valueOf(fVenc));
            } else {
                ps.setNull(11, java.sql.Types.DATE);
            }

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Guardado \nID: " + idIntangible + "\nCódigo: " + codigo);

            // limpiar
            txtNombre1.setText("");
            txtVersion.setText("");
            txtNombreProveedor.setText("");
            txtIDProveedor.setText("");
            txtCosto.setText("");
            txtVidaUtil.setText("");
            txtFechaAdq.setText("");
            txtFechaVenc.setText("");
            cmbTipo.setSelectedIndex(0);
            txtNombre1.requestFocus();

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(), "Base de datos", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVersionActionPerformed

    }//GEN-LAST:event_txtVersionActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void txtIDProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JFormattedTextField txtFechaAdq;
    private javax.swing.JFormattedTextField txtFechaVenc;
    private javax.swing.JTextField txtIDProveedor;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtVersion;
    private javax.swing.JTextField txtVidaUtil;
    // End of variables declaration//GEN-END:variables
}
